"use client";
import { useMemo, useState } from "react";
import "./supply-chain-lab.css";

const vendors=[
  {name:"Luz Cerámica",place:"Oaxaca, MX",cap:55,lead:32,quality:96,cost:18.4,moq:50,response:3,fit:["Stoneware","Low MOQ","Custom glaze"]},
  {name:"Kintsu Works",place:"Kyoto, JP",cap:28,lead:40,quality:99,cost:24.1,moq:24,response:4,fit:["Premium craft","Low MOQ","Repair story"]},
  {name:"Shenzhen Forma",place:"Shenzhen, CN",cap:310,lead:26,quality:87,cost:9.8,moq:300,response:2,fit:["Scale","Fast tooling","Cost"]},
  {name:"Terra House",place:"Los Angeles, US",cap:42,lead:18,quality:94,cost:29.6,moq:18,response:5,fit:["Domestic","Fast recovery","Small batch"]},
];
const companies=[
  {name:"Solace Hotels",type:"B2B pilot",units:120,due:"Sep 12",margin:58,risk:"Packaging approval"},
  {name:"Mina Studio",type:"Trade account",units:48,due:"Sep 20",margin:63,risk:"None"},
  {name:"Presidio Drop",type:"Creator launch",units:80,due:"Aug 28",margin:53,risk:"Margin below guardrail"},
];

export default function SupplyChainLab(){
  const [vendorIndex,setVendorIndex]=useState(0),[companyIndex,setCompanyIndex]=useState(0),[uplift,setUplift]=useState(15),[forecastError,setForecastError]=useState(18),[price,setPrice]=useState(68),[freight,setFreight]=useState(4.8),[copied,setCopied]=useState(false);
  const vendor=vendors[vendorIndex],company=companies[companyIndex];
  const model=useMemo(()=>{const demand=Math.ceil(company.units*(1+uplift/100)),low=Math.max(0,Math.round(demand*(1-forecastError/100))),high=Math.round(demand*(1+forecastError/100)),weeks=Math.max(1,Math.ceil(vendor.lead/7)),capacity=vendor.cap*weeks,landed=vendor.cost+freight+2.1+vendor.cost*.035,margin=(price-landed-price*.031)/price*100,batches=Math.ceil(demand/vendor.moq),orderQty=batches*vendor.moq,capacityGap=capacity-demand,fit=Math.round(vendor.quality*.35+Math.min(100,capacity/demand*100)*.25+Math.max(0,100-vendor.lead)*.15+Math.max(0,100-vendor.cost*2)*.15+vendor.response*20*.1);return{demand,low,high,weeks,capacity,landed,margin,batches,orderQty,capacityGap,fit}},[vendor,company,uplift,forecastError,price,freight]);
  const blockers=[model.capacityGap<0&&`${Math.abs(model.capacityGap)}-unit capacity gap`,model.margin<55&&`Margin ${model.margin.toFixed(1)}% is below 55%`,vendor.quality<90&&"Quality is below pilot threshold",company.risk!=="None"&&company.risk].filter(Boolean) as string[];
  const verdict=blockers.length?"Hold and resolve":"Approve controlled pilot";
  return <section className="science-lab panel" id="decision-science">
    <div className="science-heading"><div><p className="eyebrow">CONNECTED DECISION WORKSPACE</p><h2>Supply-chain decision lab</h2><p>Choose a company and vendor; store analytics and operating constraints produce one explainable recommendation.</p></div><span>Profile → demand → fit → scenario → decision</span></div>
    <div className="lab-context">
      <article className="store-profile"><div className="store-title"><span>MS</span><div><small>STORE PROFILE</small><h3>Fictional Maker Store</h3><p>Small-batch objects · hospitality & direct-to-consumer</p></div><b>82% ready</b></div><div className="profile-grid"><span><small>POSITIONING</small><b>Craft-led premium</b></span><span><small>MARGIN FLOOR</small><b>55%</b></span><span><small>FULFILLMENT</small><b>Made to order</b></span><span><small>QUALITY FLOOR</small><b>90 / 100</b></span></div><div className="profile-gaps"><b>Profile gaps</b><span>Packaging SLA</span><span>Returns baseline</span></div></article>
      <article className="analytics-card"><div><small>STORE ANALYTICS · 30 DAYS</small><h3>Demand is healthy; margin needs attention.</h3></div><div className="metric-row"><span><b>184</b><small>units sold</small></span><span><b>61%</b><small>gross margin</small></span><span><b>3.8%</b><small>conversion</small></span><span><b>4.2%</b><small>return rate</small></span></div><div className="signal-bar"><span style={{width:"72%"}}/><i>Stoneware demand +18% · custom glaze saves +31%</i></div></article>
    </div>
    <div className="entity-grid">
      <section className="entity-panel"><div className="entity-head"><div><p className="science-kicker">01 · COMPANY / CHANNEL</p><h3>What commitment are we serving?</h3></div><span>{companies.length} active</span></div>{companies.map((x,i)=><button key={x.name} className={i===companyIndex?"selected":""} onClick={()=>setCompanyIndex(i)}><span><b>{x.name}</b><small>{x.type} · {x.units} units · due {x.due}</small></span><em>{x.margin}% margin</em></button>)}</section>
      <section className="entity-panel"><div className="entity-head"><div><p className="science-kicker">02 · VENDOR</p><h3>Who can deliver it responsibly?</h3></div><span>{vendors.length} qualified</span></div>{vendors.map((x,i)=><button key={x.name} className={i===vendorIndex?"selected":""} onClick={()=>setVendorIndex(i)}><span><b>{x.name}</b><small>{x.place} · {x.cap}/wk · {x.lead}d</small></span><em>{x.quality} quality</em></button>)}</section>
      <aside className="vendor-profile"><p className="science-kicker">SELECTED VENDOR PROFILE</p><div className="vendor-name"><span>{vendor.name.split(" ").map(x=>x[0]).join("")}</span><div><h3>{vendor.name}</h3><p>{vendor.place}</p></div><b>{model.fit}<small>decision fit</small></b></div><div className="capability-tags">{vendor.fit.map(x=><span key={x}>{x}</span>)}</div><dl><div><dt>Capacity</dt><dd>{vendor.cap}/week</dd></div><div><dt>Lead time</dt><dd>{vendor.lead} days</dd></div><div><dt>MOQ</dt><dd>{vendor.moq}</dd></div><div><dt>Unit quote</dt><dd>${vendor.cost.toFixed(2)}</dd></div><div><dt>Quality</dt><dd>{vendor.quality}/100</dd></div><div><dt>Response modes</dt><dd>{vendor.response}/5</dd></div></dl><p className="vendor-note">Fit is constrained by minimum thresholds; it is not a price-only ranking.</p></aside>
    </div>
    <div className="decision-workbench">
      <section className="scenario-controls"><div><p className="science-kicker">03 · LIVE SCENARIO</p><h3>Stress-test the commitment</h3></div><label>Demand uplift <output>+{uplift}%</output><input type="range" min="-20" max="60" value={uplift} onChange={e=>setUplift(+e.target.value)}/></label><label>Forecast error <output>±{forecastError}%</output><input type="range" min="5" max="40" value={forecastError} onChange={e=>setForecastError(+e.target.value)}/></label><label>Retail / transfer price <output>${price}</output><input type="range" min="40" max="120" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>Freight per unit <output>${freight.toFixed(1)}</output><input type="range" min="1" max="15" step=".1" value={freight} onChange={e=>setFreight(+e.target.value)}/></label></section>
      <section className="model-output"><p className="science-kicker">MODEL OUTPUT</p><div className="output-grid"><span><small>DEMAND RANGE</small><b>{model.low}–{model.high}</b></span><span><small>ORDER PLAN</small><b>{model.orderQty}</b></span><span><small>WINDOW CAPACITY</small><b>{model.capacity}</b></span><span><small>LANDED COST</small><b>${model.landed.toFixed(2)}</b></span><span><small>CONTRIBUTION</small><b>{model.margin.toFixed(1)}%</b></span><span><small>FIT SCORE</small><b>{model.fit}/100</b></span></div><p className="model-caption">{model.batches} MOQ batch{model.batches===1?"":"es"} · {model.weeks}-week production window · capacity {model.capacityGap>=0?`${model.capacityGap} units above`:`${Math.abs(model.capacityGap)} units below`} modeled demand</p></section>
      <aside className={`decision-brief ${blockers.length?"hold":"go"}`}><p className="science-kicker">04 · DECISION BRIEF</p><h3>{verdict}</h3><p><b>{company.name}</b> with <b>{vendor.name}</b></p>{blockers.length?<ul>{blockers.map(x=><li key={x}>{x}</li>)}</ul>:<ul><li>Capacity covers modeled demand</li><li>Margin and quality clear store guardrails</li><li>Use pilot gates before scale</li></ul>}<div className="next-action"><small>NEXT BEST ACTION</small><b>{blockers.length?"Assign blockers and rerun":"Create a 50-unit pilot brief"}</b></div><button onClick={async()=>{await navigator.clipboard.writeText(`${verdict}: ${company.name} with ${vendor.name}. Demand ${model.low}–${model.high}; order ${model.orderQty}; capacity ${model.capacity}; landed cost $${model.landed.toFixed(2)}; contribution ${model.margin.toFixed(1)}%. ${blockers.length?`Blockers: ${blockers.join(", ")}`:"Guardrails cleared for a controlled pilot."}`);setCopied(true)}}>{copied?"Decision copied ✓":"Copy decision brief →"}</button></aside>
    </div>
    <div className="science-sources"><span>Methods & evidence</span><a href="https://doi.org/10.1287/mnsc.43.4.546" target="_blank" rel="noreferrer">Demand signals ↗</a><a href="https://doi.org/10.1016/j.jom.2006.02.001" target="_blank" rel="noreferrer">Supplier development ↗</a><a href="https://doi.org/10.1002/joom.1239" target="_blank" rel="noreferrer">Bottlenecks ↗</a><a href="https://doi.org/10.1016/j.jom.2014.11.002" target="_blank" rel="noreferrer">Resilience ↗</a><a href="https://doi.org/10.1287/mnsc.2013.1715" target="_blank" rel="noreferrer">Decision bias ↗</a><a href="https://doi.org/10.1287/mnsc.43.9.1258" target="_blank" rel="noreferrer">Quality systems ↗</a></div>
  </section>
}
