import "./workflow-context.css";
type View="Today"|"Sourcing"|"Pricing"|"Makers"|"Orders";
const context:Record<View,{stage:string;dreamer:string;dreamerMeta:string;maker:string;makerMeta:string;product:string;metrics:string[];people:{initials:string;name:string;role:string}[]}>= {
  Today:{stage:"Operating overview",dreamer:"Demo Operator",dreamerMeta:"Store owner · craft-led premium",maker:"Luz Cerámica",makerMeta:"Lead maker · Oaxaca",product:"Stoneware pilot + Solace Hotels",metrics:["8 open actions","2 blockers","61% avg margin"],people:[{initials:"OP",name:"Operator",role:"Decision owner"},{initials:"AM",name:"Ana",role:"Maker lead"},{initials:"MP",name:"Maya",role:"Client owner"}]},
  Sourcing:{stage:"Vendor selection",dreamer:"Fictional Maker Store",dreamerMeta:"Needs low-risk custom stoneware",maker:"4 qualified makers",makerMeta:"Luz currently leads at 92 fit",product:"50-unit controlled pilot",metrics:["≥90 quality","≤40d lead","≥55% margin"],people:[{initials:"OP",name:"Operator",role:"Sourcing owner"},{initials:"AM",name:"Ana",role:"Luz contact"},{initials:"JC",name:"Jin",role:"Forma contact"}]},
  Pricing:{stage:"Commercial decision",dreamer:"Solace Hotels",dreamerMeta:"120-unit hospitality pilot",maker:"Luz Cerámica",makerMeta:"$18.40 quote · 50 MOQ",product:"Engraved stoneware vessels",metrics:["61.2% contribution","$25.24 landed","18-unit break-even"],people:[{initials:"MP",name:"Maya",role:"Client approver"},{initials:"OP",name:"Operator",role:"Commercial owner"},{initials:"AM",name:"Ana",role:"Maker quote"}]},
  Makers:{stage:"Capability development",dreamer:"Solace Hotels",dreamerMeta:"Specs and packaging approval",maker:"8 makers · 5 countries",makerMeta:"3 actively onboarding",product:"From sample to production-ready",metrics:["3 in progress","1 approval blocked","6/8 assets ready"],people:[{initials:"OP",name:"Operator",role:"Network owner"},{initials:"AM",name:"Ana",role:"Quality partner"},{initials:"MP",name:"Maya",role:"Client approver"}]},
  Orders:{stage:"Fulfillment & recovery",dreamer:"Avery Chen",dreamerMeta:"AR-1049 · espresso set",maker:"Luz Cerámica",makerMeta:"Glaze process owner",product:"2 passed · 1 replacement",metrics:["67% packed","42 objects today","1 quality exception"],people:[{initials:"NK",name:"Noah",role:"QA owner"},{initials:"AM",name:"Ana",role:"Corrective action"},{initials:"OP",name:"Operator",role:"Customer recovery"}]},
};
export default function WorkflowContext({view}:{view:View}){const x=context[view];return <section className="workflow-context panel"><div className="workflow-stage"><small>CONNECTED CONTEXT</small><b>{x.stage}</b><span>{x.product}</span></div><div className="profile-link"><span className="profile-icon dreamer">D</span><div><small>DREAMER / CUSTOMER</small><b>{x.dreamer}</b><span>{x.dreamerMeta}</span></div></div><i>→</i><div className="profile-link"><span className="profile-icon maker">M</span><div><small>MAKER / VENDOR</small><b>{x.maker}</b><span>{x.makerMeta}</span></div></div><div className="context-metrics">{x.metrics.map(m=><span key={m}>{m}</span>)}</div><div className="context-people"><small>PEOPLE IN THIS HANDOFF</small><div>{x.people.map(p=><span key={p.name} title={`${p.name} · ${p.role}`}><i>{p.initials}</i><b>{p.name}</b><small>{p.role}</small></span>)}</div></div></section>}
